defaults:
  - template_robocasa

name: robocasa_CloseBlenderLid
hdf5_path_globs: /data/shared_workspace/zhangshiqi/dataset/robocasa/hdf5/CloseBlenderLid.hdf5
buffer_path: /data/shared_workspace/zhangshiqi/dataset/robocasa/zarr/CloseBlenderLid.zarr
