defaults:
  - template_robocasa

name: robocasa_NavigateKitchen
hdf5_path_globs: /data/shared_workspace/zhangshiqi/dataset/robocasa/hdf5/NavigateKitchen.hdf5
buffer_path: /data/shared_workspace/zhangshiqi/dataset/robocasa/zarr/NavigateKitchen.zarr
