defaults:
  - template_robocasa

name: robocasa_TurnOffStove
hdf5_path_globs: /data/shared_workspace/zhangshiqi/dataset/robocasa/hdf5/TurnOffStove.hdf5
buffer_path: /data/shared_workspace/zhangshiqi/dataset/robocasa/zarr/TurnOffStove.zarr
